// src/components/widgets/ChallengeCard.tsx
import { Challenge } from "@/types/challenge";
import {
	Box,
	ButtonBase,
	Card,
	CardContent,
	Chip,
	Divider,
	Rating,
	Tooltip,
	Typography,
} from "@mui/material";
import Icon from "@mdi/react";
import { mdiCheck, mdiStar, mdiStarOutline } from "@mdi/js";
import { useThemeStore } from "@/store/theme";
import UIcon from "@/components/ui/UIcon";
import { hexToRGBA } from "@/utils/color";

export default function ChallengeCard({
	challenge,
}: {
	challenge: Challenge;
}): JSX.Element {
	const themeStore = useThemeStore();

	const isSolved: boolean = challenge.solved ? true : false;

	const bgColor = () => {
		switch (themeStore.mode) {
			case "dark":
				return isSolved
					? hexToRGBA(challenge?.category?.color as string, 0.6)
					: hexToRGBA(challenge?.category?.color as string, 0.2);
			case "light":
			default:
				return isSolved
					? hexToRGBA(challenge?.category?.color as string, 1)
					: hexToRGBA(challenge?.category?.color as string, 0.1);
		}
	};

	const chipColor = isSolved
		? hexToRGBA("#FFFFFF", 0.1)
		: hexToRGBA(challenge?.category?.color as string, 0.1);

	const textColor = () => {
		switch (themeStore.mode) {
			case "dark":
				return isSolved
					? hexToRGBA("#FFFFFF", 1)
					: hexToRGBA("#FFFFFF", 0.9);
			case "light":
			default:
				return isSolved
					? hexToRGBA("#FFFFFF", 1)
					: challenge?.category?.color;
		}
	};

	return (
		<Card
			sx={{
				width: 275,
				height: 150,
				backgroundColor: bgColor,
				position: "relative",
				cursor: "pointer",
				zIndex: 0,
			}}
		>
			<CardContent>
				<Chip
					label={challenge?.category?.name}
					size="small"
					sx={{
						fontSize: "0.75rem",
						fontWeight: "500",
						mb: "0.25rem",
						bgcolor: chipColor,
						color: textColor,
					}}
				/>
				<Typography
					variant="h6"
					sx={{
						fontWeight: "bold",
						width: 200,
						overflow: "hidden",
						whiteSpace: "nowrap",
						textOverflow: "ellipsis",
						my: 1,
					}}
					color={textColor}
				>
					{challenge.title}
				</Typography>
				<Divider
					sx={{
						my: 1,
						bgcolor: textColor,
						borderColor: textColor,
						zIndex: 1,
					}}
				/>
				<Box
					style={{
						display: "flex",
						justifyContent: "space-between",
						alignItems: "center",
					}}
				>
					<Typography
						sx={{ m: 1, fontWeight: "bold", color: textColor }}
					>
						{challenge.pts} pts
					</Typography>
					<Rating
						readOnly
						value={challenge.difficulty}
						sx={{
							color: textColor,
							"& .MuiRating-iconEmpty": {
								color: textColor,
							},
						}}
						size="large"
						icon={<Icon path={mdiStar} size={1.25} />}
						emptyIcon={<Icon path={mdiStarOutline} size={1.25} />}
					/>
				</Box>
			</CardContent>
			{isSolved && (
				<Box
					sx={{
						position: "absolute",
						top: "0.75rem",
						right: "0.75rem",
						zIndex: 1,
						color: textColor,
					}}
				>
					<Tooltip title="已解决" placement="top">
						<Icon path={mdiCheck} size={1.25}></Icon>
					</Tooltip>
				</Box>
			)}
			<Box
				sx={{
					position: "absolute",
					right: "-1rem",
					bottom: "-2.5rem",
					zIndex: -1,
					opacity: 0.2,
					fontSize: "3rem",
					color: textColor,
				}}
			>
				<UIcon path={`mdi${challenge.category?.icon}`} size={8} />
			</Box>
		</Card>
	);
}

// components/widgets/ChallengeCard.vue
<template>
	<v-card
		class="challenge-card no-select"
		:variant="challenge.is_solved ? 'elevated' : 'tonal'"
		:color="challenge.category.color"
		elevation="3"
		@click="dialog = true"
	>
		<v-card-item>
			<div>
				<v-chip
					size="small"
					style="
						font-size: 0.75rem !important;
						font-weight: 500;
						line-height: 2rem;
						text-transform: capitalize !important;
						margin-bottom: 0.25rem;
					"
				>
					{{ challenge.category.name }}
				</v-chip>
				<div
					class="text-h6 my-1 font-weight-bold"
					style="
						width: 200px;
						white-space: nowrap;
						text-overflow: ellipsis;
						overflow: hidden;
					"
				>
					{{ challenge.title }}
				</div>
				<v-divider thickness="2" />
				<div class="d-flex flex-wrap justify-space-between">
					<div class="ma-2 pa-2 font-weight-bold">
						{{ challenge.pts }} pts
					</div>
					<div class="d-flex justify-center align-center">
						<v-rating
							:readonly="true"
							:length="5"
							:size="24"
							:model-value="challenge.difficulty"
						/>
					</div>
				</div>
			</div>
		</v-card-item>
		<v-tooltip text="已解决" location="top center">
			<template #activator="{ props: tooltip }">
				<v-icon
					v-show="challenge.is_solved"
					class="check"
					icon="mdi-check"
					style="position: absolute; right: 15px; top: 15px"
					v-bind="tooltip"
				/>
			</template>
		</v-tooltip>
		<v-icon
			size="200"
			style="
				position: absolute;
				right: -20px;
				bottom: -25px;
				z-index: -1;
				opacity: 0.2;
			"
			:icon="`mdi-${challenge.category.icon}`"
		/>
		<ChallengeDialog v-model="dialog" :challenge="challenge" />
	</v-card>
</template>

<script setup lang="ts">
import ChallengeDialog from "@/components/modals/ChallengeDialog.vue";
import type { Challenge } from "@/types/challenge";

const dialog = ref(false);
interface Props {
	challenge: Challenge;
}

const props = withDefaults(defineProps<Props>(), {
	challenge: null,
});
</script>

<style scoped lang="scss">
.challenge-card {
	width: 275px;
	height: 150px;
}
.container {
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}
</style>
