// src/components/modals/ChallengeDialog.tsx
import { Challenge } from "@/types/challenge";
import {
	Box,
	Button,
	Card,
	Divider,
	IconButton,
	InputAdornment,
	TextField,
	Tooltip,
} from "@mui/material";
import UIcon from "@/components/ui/UIcon";
import {
	mdiFlag,
	mdiServerNetwork,
	mdiOpenInNew,
	mdiDownload,
	mdiHexagonSlice6,
	mdiHexagonSlice4,
	mdiHexagonSlice2,
	mdiPackageVariant,
} from "@mdi/js";
import { useSubmissionApi } from "@/api/submission";
import { useSnackBarStore } from "@/store/snackBar";
import { useChallengeStore } from "@/store/challenge";
import { usePodStore } from "@/store/pod";
import Icon from "@mdi/react";
import Markdown from "@/components/ui/Markdown";
import { useEffect, useState } from "react";
import { Submission } from "@/types/submission";
import { usePodApi } from "@/api/pod";
import { LoadingButton } from "@mui/lab";
import { Instance } from "@/types/instance";
import { useTeamStore } from "@/store/team";
import { useGameStore } from "@/store/game";
import { useMediaApi } from "@/api/media";
import { saveAs } from "file-saver";

export default function ChallengeDialog({
	challenge,
	mode,
}: {
	challenge?: Challenge;
	mode: "practice" | "game";
}) {
	const submissionApi = useSubmissionApi();
	const podApi = usePodApi();
	const mediaApi = useMediaApi();

	const snackBarStore = useSnackBarStore();
	const challengeStore = useChallengeStore();
	const podStore = usePodStore();
	const teamStore = useTeamStore();
	const gameStore = useGameStore();

	function downloadAttachment() {
		let info: any = {};
		mediaApi
			.getChallengeAttachmentInfoByChallengeID(challenge?.id as number)
			.then((res) => {
				const r = res.data;
				if (r.code !== 200) {
					snackBarStore.error("获取附件信息失败");
					return;
				}
				info = r;
				mediaApi
					.getChallengeAttachmentByChallengeID(
						challenge?.id as number
					)
					.then((res) => {
						const r = res.data;
						const blob = new Blob([r]);
						saveAs(blob, info?.file_name || "attachment");
					});
			});
	}

	// Flag 输入框
	const [flag, setFlag] = useState<string>("");

	// 容器相关
	const [podID, setPodID] = useState<number>(0);
	const [podInstances, setPodInstances] = useState<Array<Instance>>([]);
	const [podCreateLoading, setPodCreateLoading] = useState<boolean>(false);
	const [podRemoveLoading, setPodRemoveLoading] = useState<boolean>(false);
	const [podRenewLoading, setPodRenewLoading] = useState<boolean>(false);

	useEffect(() => {
		if (podStore?.existPods && challenge?.id) {
			const pod = podStore?.existPods[challenge?.id];
			if (pod) {
				setPodID(pod.id);
				setPodInstances(pod.instances);
			}
		}
	}, []);

	// 重定向
	function redirectTo(url: string) {
		window.open(`http://${url}`, "_blank");
	}

	// Flag 提交
	function handleSubmit() {
		if (flag === "") {
			snackBarStore.error("Flag 不能为空");
			return;
		}
		snackBarStore.info("判题中");
		submissionApi
			.createSubmission({
				challenge_id: challenge?.id as number,
				flag: flag,
				team_id:
					mode === "game" ? teamStore?.selectedTeamID : undefined,
				game_id:
					mode === "game" ? gameStore?.selectedGameID : undefined,
			})
			.then((res) => {
				const r = res.data;
				if (r.code === 200) {
					switch (r.status) {
						case 1:
							snackBarStore.warning("错误");
							break;
						case 2:
							snackBarStore.success("正确");
							setFlag("");
							challengeStore.setRefresh(challenge?.id as number);
							break;
						case 3:
							snackBarStore.error("作弊");
							break;
						case 4:
							snackBarStore.info("重复提交");
							setFlag("");
							challengeStore.setRefresh(challenge?.id as number);
							break;
					}
				}
			});
	}

	// 容器创建
	function handlePodCreate() {
		snackBarStore.info("创建中");
		setPodCreateLoading(true);
		podApi
			.createPod({
				challenge_id: challenge?.id as number,
				team_id:
					mode === "game" ? teamStore?.selectedTeamID : undefined,
				game_id:
					mode === "game" ? gameStore?.selectedGameID : undefined,
			})
			.then((res) => {
				const r = res.data;
				if (r.code === 200) {
					setPodID(r.id);
					setPodInstances(r.instances);
					podStore.addExistPod(challenge?.id as number, r);
					snackBarStore.success("创建成功");
				}
			})
			.catch((err) => {
				snackBarStore.error(`创建失败 ${err}`);
			})
			.finally(() => {
				setPodCreateLoading(false);
			});
	}

	// 容器移除
	function handlePodRemove() {
		snackBarStore.info("删除中");
		setPodRemoveLoading(true);
		podApi
			.removePod({
				id: podID,
			})
			.then((res) => {
				const r = res.data;
				if (r.code === 200) {
					snackBarStore.success("删除成功");
				}
			})
			.catch((err) => {
				snackBarStore.error(`删除失败 ${err}`);
			})
			.finally(() => {
				setPodID(0);
				setPodInstances([]);
				setPodRemoveLoading(false);
			});
	}

	// 容器续期
	function handlePodRenew() {
		snackBarStore.info("续期中");
		setPodRenewLoading(true);
		podApi
			.removePod({
				id: podID,
			})
			.then((res) => {
				const r = res.data;
				if (r.code === 200) {
					snackBarStore.success("续期成功");
				}
			})
			.catch((err) => {
				snackBarStore.error(`续期失败 ${err}`);
			})
			.finally(() => {
				setPodRenewLoading(false);
			});
	}

	return (
		<Card
			sx={{
				width: "40rem",
				minHeight: "20rem",
				padding: "1rem",
				display: "flex",
				flexDirection: "column",
				justifyContent: "space-between",
			}}
		>
			<Box>
				<Box
					sx={{
						display: "flex",
						alignItems: "center",
						justifyContent: "space-between",
					}}
				>
					<Box
						sx={{
							display: "flex",
							alignItems: "center",
						}}
					>
						<Box
							sx={{
								color: challenge?.category?.color,
								display: "flex",
								alignItems: "center",
							}}
						>
							<UIcon
								path={`mdi${challenge?.category?.icon}`}
								size={1}
							/>
						</Box>
						<Box
							sx={{ fontWeight: "bold", marginX: "0.5rem" }}
							className={"no-select"}
						>
							{challenge?.title}
						</Box>
					</Box>
					<Box
						sx={{
							display: "flex",
							alignItems: "center",
						}}
					>
						{(challenge?.submissions?.length as number) > 0 && (
							<Tooltip
								title={`一血 ${(challenge?.submissions as Array<Submission>)[0]?.user?.nickname}`}
								placement={"top"}
							>
								<Icon
									path={mdiHexagonSlice6}
									size={1}
									color={"#fcc419"}
								/>
							</Tooltip>
						)}
						{(challenge?.submissions?.length as number) > 1 && (
							<Tooltip
								title={`二血 ${(challenge?.submissions as Array<Submission>)[1]?.user?.nickname}`}
								placement={"top"}
							>
								<Icon
									path={mdiHexagonSlice4}
									size={1}
									color={"#a6a6a6"}
								/>
							</Tooltip>
						)}
						{(challenge?.submissions?.length as number) > 2 && (
							<Tooltip
								title={`三血 ${(challenge?.submissions as Array<Submission>)[2]?.user?.nickname}`}
								placement={"top"}
							>
								<Icon
									path={mdiHexagonSlice2}
									size={1}
									color={"#f98539"}
								/>
							</Tooltip>
						)}
					</Box>
				</Box>
				<Divider sx={{ marginY: "1rem" }} />
				<Box sx={{ display: "flex", justifyContent: "space-between" }}>
					<Box sx={{ flexGrow: 1 }}>
						<Markdown content={challenge?.description} />
					</Box>
					{challenge?.has_attachment && (
						<Box>
							<IconButton
								sx={{
									color: challenge?.category?.color,
								}}
								onClick={downloadAttachment}
							>
								<Icon path={mdiDownload} size={1} />
							</IconButton>
						</Box>
					)}
				</Box>
			</Box>
			<Box sx={{ marginTop: "2.5rem" }}>
				{challenge?.is_dynamic && (
					<>
						<Box
							sx={{
								display: "flex",
								flexDirection: "column",
								marginTop: "1rem",
							}}
						>
							{podInstances?.map((instance, index) => (
								<>
									<Box
										sx={{
											display: "flex",
											alignItems: "center",
											paddingX: "0.5rem",
											marginTop: "1rem",
										}}
									>
										<Icon
											path={mdiPackageVariant}
											size={1}
										/>
										<Box
											sx={{
												marginX: "0.5rem",
												fontWeight: "bold",
											}}
										>
											容器 {index + 1}
										</Box>
									</Box>
									{instance.nats?.map((nat) => (
										<TextField
											size="small"
											variant="filled"
											hiddenLabel
											value={nat.entry}
											sx={{
												"& .MuiFilledInput-root::after":
													{
														borderBottomColor:
															challenge?.category
																?.color,
													},
												flexGrow: 1,
												marginTop: "0.5rem",
											}}
											InputProps={{
												startAdornment: (
													<InputAdornment position="start">
														<Box
															sx={{
																display: "flex",
																alignItems:
																	"center",
															}}
														>
															<Icon
																path={
																	mdiServerNetwork
																}
																size={1}
															/>
															<Box
																sx={{
																	marginX:
																		"0.5rem",
																}}
															>
																{nat.src_port} →
															</Box>
														</Box>
													</InputAdornment>
												),
												endAdornment: (
													<InputAdornment
														position="end"
														sx={{
															cursor: "pointer",
														}}
														onClick={() => {
															redirectTo(
																"0.0.0.0"
															);
														}}
													>
														<Icon
															path={mdiOpenInNew}
															size={1}
														/>
													</InputAdornment>
												),
											}}
										/>
									))}
								</>
							))}
						</Box>
						<Box
							sx={{
								marginY: "1rem",
								display: "flex",
								justifyContent: "space-between",
								alignItems: "center",
							}}
						>
							<Box>
								<Box
									sx={{
										fontSize: "0.8rem",
										fontWeight: "bold",
									}}
								>
									本题为容器题目，解题需开启容器实例
								</Box>
								<Box
									sx={{ fontSize: "0.8rem" }}
									color={"text.secondary"}
								>
									本题容器时间 {challenge?.duration}s
								</Box>
							</Box>
							<Box sx={{ display: "flex" }}>
								{podID > 0 && (
									<>
										<LoadingButton
											variant="contained"
											disableElevation
											loading={podRenewLoading}
											sx={{
												bgcolor: "#3b81f5",
												"&:hover": {
													bgcolor: "#3b81f5",
												},
												fontWeight: "bold",
												color: "#FFF",
												marginX: "0.25rem",
											}}
											onClick={handlePodRenew}
										>
											实例续期
										</LoadingButton>
										<LoadingButton
											variant="contained"
											disableElevation
											loading={podRemoveLoading}
											sx={{
												bgcolor: "#d22e2d",
												"&:hover": {
													bgcolor: "#d22e2d",
												},
												fontWeight: "bold",
												color: "#FFF",
												marginX: "0.25rem",
											}}
											onClick={handlePodRemove}
										>
											销毁实例
										</LoadingButton>
									</>
								)}
								{podID === 0 && (
									<LoadingButton
										variant="contained"
										disableElevation
										loading={podCreateLoading}
										sx={{
											bgcolor: challenge?.category?.color,
											"&:hover": {
												bgcolor:
													challenge?.category?.color,
											},
											fontWeight: "bold",
											color: "#FFF",
											marginX: "0.25rem",
										}}
										onClick={handlePodCreate}
									>
										开启实例
									</LoadingButton>
								)}
							</Box>
						</Box>
					</>
				)}
				<Divider sx={{ marginY: "1rem" }} />
				<Box sx={{ display: "flex", alignItems: "center" }}>
					<TextField
						size="small"
						variant="filled"
						hiddenLabel
						placeholder={"Flag"}
						value={flag}
						onChange={(e) => setFlag(e.target.value)}
						sx={{
							"& .MuiFilledInput-root::after": {
								borderBottomColor: challenge?.category?.color,
							},
							flexGrow: 1,
							marginRight: "0.5rem",
						}}
						InputProps={{
							startAdornment: (
								<InputAdornment position="start">
									<Icon path={mdiFlag} size={1} />
								</InputAdornment>
							),
						}}
					/>
					<Button
						variant="contained"
						disableElevation
						sx={{
							bgcolor: challenge?.category?.color,
							"&:hover": {
								bgcolor: challenge?.category?.color,
							},
							fontWeight: "bold",
							color: "#FFF",
						}}
						onClick={handleSubmit}
					>
						提交
					</Button>
				</Box>
			</Box>
		</Card>
	);
}

// components/modals/ChallengeDialog.vue
<template>
	<v-dialog width="600">
		<v-card min-height="300" class="pa-5">
			<div class="d-flex justify-space-between">
				<div class="d-flex">
					<v-icon
						:color="challenge.category.color"
						:icon="`mdi-${challenge.category.icon}`"
					/>
					<div
						class="font-weight-bold ml-2"
						style="
							width: 20rem;
							white-space: nowrap;
							text-overflow: ellipsis;
							overflow: hidden;
						"
					>
						{{ challenge.title }}
					</div>
				</div>
				<div class="d-flex">
					<v-tooltip
						v-if="challenge.submissions?.length > 0"
						location="top"
					>
						<template #activator="{ props: p }">
							<v-icon
								v-bind="p"
								icon="mdi-hexagon-slice-6"
								color="#fcc419"
							></v-icon>
						</template>
						一血：{{ challenge.submissions[0].user.nickname }}
					</v-tooltip>
					<v-tooltip
						v-if="challenge.submissions?.length > 1"
						location="top"
					>
						<template #activator="{ props: p }">
							<v-icon
								v-bind="p"
								icon="mdi-hexagon-slice-4"
								color="#a6a6a6"
							></v-icon>
						</template>
						二血：{{ challenge.submissions[1].user.nickname }}
					</v-tooltip>
					<v-tooltip
						v-if="challenge.submissions?.length > 2"
						location="top"
					>
						<template #activator="{ props: p }">
							<v-icon
								v-bind="p"
								icon="mdi-hexagon-slice-2"
								color="#f98539"
							></v-icon>
						</template>
						三血：{{ challenge.submissions[2].user.nickname }}
					</v-tooltip>
				</div>
			</div>
			<v-divider class="my-3" />
			<div class="d-flex justify-space-between">
				<div class="description flex-1-0">
					<Markdown :content="challenge.description" />
				</div>
				<div>
					<v-list-item
						v-if="challenge.has_attachment"
						variant="tonal"
						:nav="true"
						:base-color="challenge.category.color"
						class="d-flex align-center justify-center"
						@click="downloadAttachment()"
					>
						<v-icon icon="mdi-download" />
						<v-tooltip activator="parent" location="bottom center"
							>下载附件</v-tooltip
						>
					</v-list-item>
				</div>
			</div>
			<v-spacer class="my-5" />
			<div v-if="challenge.is_dynamic">
				<v-list lines="two">
					<v-list-item v-for="i in instances?.length" :key="i">
						<template #title>
							<v-icon icon="mdi-package-variant-closed"></v-icon>
							<span class="mx-2">容器 {{ i }}</span>
						</template>
						<div
							v-for="nat in instances[i - 1]?.nats"
							:key="nat.id"
						>
							<v-text-field
								v-model="nat.entry"
								prepend-inner-icon="mdi-server-network"
								hide-details
								density="compact"
								placeholder="容器实例地址"
								:single-line="true"
								:readonly="true"
								variant="solo-filled"
								:flat="true"
								class="my-1"
							>
								{{ nat.src_port }} →&nbsp;
								<template v-if="nat.entry" #append-inner>
									<v-tooltip
										location="top center"
										text="打开"
									>
										<template #activator="{ props: prop }">
											<v-icon
												icon="mdi-open-in-new"
												v-bind="prop"
												@click="redirectTo(nat.entry)"
											></v-icon>
										</template>
									</v-tooltip>
								</template>
							</v-text-field>
						</div>
					</v-list-item>
				</v-list>
				<div class="d-flex justify-space-between align-end my-3">
					<div>
						<div class="font-weight-bold text-caption">
							本题为动态容器题目，解题需开启容器实例
						</div>
						<div
							v-if="!podRunning"
							class="font-weight-thin text-caption"
						>
							本题容器时间 {{ challenge.duration }}s
						</div>
						<div
							v-if="podRunning"
							class="font-weight-thin text-caption"
						>
							本题容器剩余时间 {{ timeLeft }}s
						</div>
					</div>
					<div class="d-flex">
						<v-btn
							v-show="podRunning"
							:disabled="podRemovePending"
							:loading="podRenewPending"
							color="blue"
							variant="flat"
							class="ml-2"
							@click="renewPod()"
						>
							<span class="font-weight-bold">延长时间</span>
						</v-btn>
						<v-btn
							v-show="podRunning"
							color="red-darken-2"
							variant="flat"
							class="ml-2"
							:loading="podRemovePending"
							@click="removePod()"
						>
							<span class="font-weight-bold">销毁实例</span>
						</v-btn>
						<v-btn
							v-show="!podRunning"
							:color="challenge.category.color"
							variant="flat"
							class="ml-2"
							:loading="podCreatePending"
							@click="createPod()"
						>
							<span class="font-weight-bold">开启实例</span>
						</v-btn>
					</div>
				</div>
			</div>
			<v-divider class="my-3" />
			<div class="d-flex align-center">
				<v-text-field
					v-model="flag"
					prepend-inner-icon="mdi-flag"
					hide-details
					density="compact"
					placeholder="Flag"
					:clearable="true"
				/>
				<v-btn
					:color="challenge.category.color"
					variant="flat"
					class="ml-2"
					@click="submit()"
				>
					<span class="font-weight-bold">提交</span>
				</v-btn>
			</div>
		</v-card>
	</v-dialog>
</template>

<script setup lang="ts">
import { saveAs } from "file-saver";
import Markdown from "@/components/utils/Markdown.vue";
import { createSubmission } from "@/api/submission";
import {
	createPod as createPodApi,
	removePod as removePodApi,
	renewPod as renewPodApi,
	getPod as getPodApi,
} from "@/api/pod";
import { useSnackBarStore } from "@/store/snackBar";
import { usePodStore } from "@/store/pod";
import { useChallengeStore } from "@/store/challenge";
import type { Challenge } from "@/types/challenge";
import type { PodCreateResponse, PodRenewResponse } from "@/types/pod";
import {
	getChallengeAttachment,
	getChallengeAttachmentInfo,
} from "@/api/media";
import { ref, watch } from "vue";

const snackBarStore = useSnackBarStore();
const podStore = usePodStore();
const challengeStore = useChallengeStore();

interface Props {
	challenge: Challenge;
}
const props = defineProps<Props>();

const podRunning = ref(false);
const podRemovePending = ref(false);
const podCreatePending = ref(false);
const podRenewPending = ref(false);
const podID = ref(0);
const podRemovedAt = ref(0);

const instances = ref(Array<any>());

const timeLeft = ref(0);

const flag = ref("");

watch(podStore.existPods, () => {
	if (props.challenge.id in podStore.existPods) {
		podRunning.value = true;
		podID.value = podStore.existPods[props.challenge.id]?.id;
		instances.value = podStore.existPods[props.challenge.id]?.instances;
		podRemovedAt.value = podStore.existPods[props.challenge.id]?.removed_at;
	}
});

function redirectTo(url: string) {
	window.open(`http://${url}`, "_blank");
}

async function submit() {
	const response = await createSubmission({
		challenge_id: props.challenge.id,
		flag: flag.value,
		team_id: null,
		game_id: null,
	});
	if (response?.code === 200) {
		if (response?.status === 1) {
			snackBarStore.warning("答案错误");
		} else if (response?.status === 2) {
			for (let i = 0; i < challengeStore.challenges.length; i++) {
				if (challengeStore.challenges[i].id === props.challenge.id) {
					challengeStore.challenges[i].is_solved = true;
				}
			}
			snackBarStore.success("答案正确");
			flag.value = "";
			challengeStore.refreshChallenges();
		} else if (response?.status === 3) {
			snackBarStore.error("作弊");
		} else if (response?.status === 4) {
			for (let i = 0; i < challengeStore.challenges.length; i++) {
				if (challengeStore.challenges[i].id === props.challenge.id) {
					challengeStore.challenges[i].is_solved = true;
				}
			}
			snackBarStore.info("你已经做出过这道题了");
			flag.value = "";
		}
	} else {
		snackBarStore.error(response.msg);
	}
}

async function createPod() {
	podCreatePending.value = true;
	const { pending, data: res } = await createPodApi({
		challenge_id: props.challenge.id,
	});
	podCreatePending.value = pending.value;
	watch(pending, (newVal) => {
		podCreatePending.value = newVal;
	});
	const resObj = res.value as PodCreateResponse;
	if (resObj?.code === 200) {
		podID.value = resObj?.id;
		instances.value = resObj?.instances;
		podRemovedAt.value = resObj?.removed_at;
		podRunning.value = true;
		snackBarStore.success("容器实例已开启");
	} else {
		snackBarStore.error("容器实例开启失败\n" + resObj?.msg);
	}
}

async function removePod() {
	podRemovePending.value = true;
	const instanceStatus = await getPodById();
	if (instanceStatus === "running") {
		interface Response {
			code: number;
			msg: string;
		}
		const { pending, data: res } = await removePodApi({
			id: podID.value,
		});
		podRemovePending.value = pending.value;
		watch(pending, (newVal) => {
			podRemovePending.value = newVal;
		});
		const resObj = res.value as Response;
		if (resObj?.code === 200) {
			podRunning.value = false;
			instances.value = [];
			snackBarStore.success("容器实例移除成功");
		} else {
			snackBarStore.error("容器实例移除失败\n" + resObj?.msg);
		}
	} else {
		podRemovePending.value = false;
		podRunning.value = false;
		instances.value = [];
		snackBarStore.warning("容器实例已被移除");
	}
}

async function renewPod() {
	podRenewPending.value = true;
	const instanceStatus = await getPodById();
	if (instanceStatus === "running") {
		const { pending, data: res } = await renewPodApi({
			id: podID.value,
		});
		const resObj = res.value as PodRenewResponse;
		podRenewPending.value = pending.value;
		watch(pending, (newVal) => {
			podRenewPending.value = newVal;
		});
		if (resObj?.code === 200) {
			podRemovedAt.value = resObj?.removed_at;
			snackBarStore.success("容器实例续期成功");
		} else {
			snackBarStore.error("容器实例续期失败\n" + resObj?.msg);
		}
	} else {
		podRenewPending.value = false;
		podRunning.value = false;
		snackBarStore.warning("容器实例已被移除，无法续期");
	}
}

async function getPodById() {
	const response = await getPodApi(`id=${podID.value}`);
	if (response?.code === 200) {
		if (response?.data[0]?.status === "running") {
			podRunning.value = true;
			return "running";
		} else if (response?.data[0]?.status === "removed") {
			podRunning.value = false;
			return "removed";
		}
	}
}

async function downloadAttachment() {
	const info = await getChallengeAttachmentInfo(props.challenge.id);
	if (info.code === 200) {
		const b = await getChallengeAttachment(props.challenge.id);
		const blob = new Blob([b as BlobPart], {
			type: "application/octet-stream",
		});
		saveAs(blob, info.file_name);
	} else {
		snackBarStore.error("附件获取失败，请检查附件是否存在");
	}
}

function updateTime() {
	const timeNow = new Date().getTime();
	timeLeft.value = Math.round(podRemovedAt.value - timeNow / 1000);
	if (timeLeft.value <= 0) {
		podRunning.value = false;
	}
}

updateTime();
setInterval(updateTime, 1000);
</script>
